{
 "title": "MetroPT Dashboard",
 "time": { "from": "2022-01-01T21:57:02.000Z", "to": "2022-01-15T13:50:03.000Z" },
 "panels": [
  { "title": "Datos analógicos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatura del aceite",
   "type": "timeseries",
   "description": "Temperatura del aceite del compresor en grados Celsius.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT __time, Oil_temperature FROM lecturas_filtradas WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT __time, Oil_temperature FROM lecturas_filtradas WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    },
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT __time, Oil_temperature FROM lecturas_gps_alert WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT __time, Oil_temperature FROM lecturas_gps_alert WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    },
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT __time, Oil_temperature FROM lecturas_anomalas_alert WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT __time, Oil_temperature FROM lecturas_anomalas_alert WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Presión en válvula TP3  ",
   "type": "timeseries",
   "description": "Presión generada en el panel neumático.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT __time, TP3 FROM lecturas_filtradas WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT __time, TP3 FROM lecturas_filtradas WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    },
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT __time, TP3 FROM lecturas_gps_alert WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT __time, TP3 FROM lecturas_gps_alert WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    },
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT __time, TP3 FROM lecturas_anomalas_alert WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT __time, TP3 FROM lecturas_anomalas_alert WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  { "title": "Señales digitales", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "LPS",
   "type": "timeseries",
   "description": "Estado de la señal LPS, que se activa cuando la presión cae por debajo de los 7 bares.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT __time, LPS FROM lecturas_filtradas WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT __time, LPS FROM lecturas_filtradas WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    },
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT __time, LPS FROM lecturas_gps_alert WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT __time, LPS FROM lecturas_gps_alert WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    },
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT __time, LPS FROM lecturas_anomalas_alert WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT __time, LPS FROM lecturas_anomalas_alert WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "GPS_QUALITY",
   "type": "timeseries",
   "description": "Estado de la señal GPS. 1 = Señal, 0 = Falta de señal.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT __time, gpsQuality FROM lecturas_filtradas WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT __time, gpsQuality FROM lecturas_filtradas WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    },
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT __time, gpsQuality FROM lecturas_anomalas_alert WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT __time, gpsQuality FROM lecturas_anomalas_alert WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    },
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT __time, gpsQuality FROM lecturas_gps_alert WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT __time, gpsQuality FROM lecturas_gps_alert WHERE __time BETWEEN '2022-03-24T00:00:00' AND '2022-03-30T00:00:00'\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  { "title": "Mapas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Averías",
   "type": "geomap",
   "description": "Mapa que muestras las posiciones geográficas donde se ha detectado una activación de la señal LPS.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT __time, gpsLat, gpsLong, TP3 FROM lecturas_anomalas_alert WHERE __time BETWEEN '2022-02-10T00:00:00' AND '2022-02-15T00:00:00'",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT __time, gpsLat, gpsLong, TP3 FROM lecturas_anomalas_alert WHERE __time BETWEEN '2022-02-10T00:00:00' AND '2022-02-15T00:00:00'\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  }
 ]
}