{
 "title": "Kafka Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Rendimiento global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consumo de CPU",
   "type": "timeseries",
   "description": "Uso promedio de CPU por parte de Kafka, tomando un minuto como intervalo.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\"}[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de Memoria JVM",
   "type": "timeseries",
   "description": "Uso de memoria por parte de Kafka.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Entrada de datos (B/s)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Tópico: Lecturas  |  Bytes/s escritos",
   "type": "timeseries",
   "description": "Tasa de escritura en el tópico \"lecturas\".",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "LecturasBytesInPerSec_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tópico: LecturasFiltradas  |  Bytes/s escritos",
   "type": "timeseries",
   "description": "Tasa de escritura en el tópico \"lecturas_filtradas\".",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "LecturasFiltradasBytesInPerSecond",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tópico: Lecturas_Anomalas_Alert | Bytes/s escritos",
   "type": "timeseries",
   "description": "Tasa de escritura en el tópico \"lecturas_anomalas_alert\".",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "LecturasAnomalasAlertBytesInPerSecond",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tópico: Lecturas_Gps_Alert |  Bytes/s escritos",
   "type": "timeseries",
   "description": "Tasa de escritura en el tópico \"lecturas_gps_alert\".",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "LecturasGpsAlertBytesInPerSecond",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Salida de Datos (B/s)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Tópico: Lecturas | Bytes/s leídos",
   "type": "timeseries",
   "description": "Tasa de lectura en el tópico \"lecturas\".",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "LecturasBytesOutPerSecond", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tópico: LecturasFiltradas  |  Bytes/s leídos",
   "type": "timeseries",
   "description": "Tasa de lectura en el tópico \"lecturas_filtradas\".",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "LecturasFiltradasBytesOutPerSecond",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tópico: Lecturas_Anomalas_Alert | Bytes/s leídos",
   "type": "timeseries",
   "description": "Tasa de lectura en el tópico \"lecturas_anomalas_alert\".",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "LecturasAnomalasAlertBytesOutPerSecond",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tópico: Lecturas_Gps_Alert | Bytes/s leídos",
   "type": "timeseries",
   "description": "Tasa de lectura en el tópico \"lecturas_gps_alert\".",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "LecturasGpsAlertBytesOutPerSecond",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Entrada de datos (Mensajes/s)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Tópico: Lecturas  |  Mensajes/s escritos",
   "type": "timeseries",
   "description": "Tasa de escritura en mensajes en el tópico \"lecturas\".",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "LecturasMessagesInPerSecond", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tópico: Lecturas Filtradas  |  Mensajes/s escritos",
   "type": "timeseries",
   "description": "Tasa de escritura en mensajes en el tópico \"lecturas_filtradas\".",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "LecturasFiltradasMessagesInPerSecond",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tópico: Lecturas_Anomalas_Alert | Mensajes/s escritos",
   "type": "timeseries",
   "description": "Tasa de escritura en mensajes en el tópico \"lecturas_anomalas_alert\".",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "LecturasAnomalasAlertMessagesInPerSecond",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tópico: Lecturas_Gps_Alert | Mensajes/s escritos",
   "type": "timeseries",
   "description": "Tasa de escritura en mensajes en el tópico \"lecturas_gps_alert\".",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "LecturasGpsAlertMessagesInPerSecond",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}